---
swagger: '2.0'
info:
  version: 2.12.0
  title: GeoServer Styles
  description: Test of Swagger API showing current state of GeoServer /styles endpoint.

paths:
  /styles:
    get:
      operationId: getStyleList
      summary: Get a list of styles
      description: Displays a list of all styles on the server. Use the "Accept:" header to specify format, or append an extension to the endpoint (example "/styles.xml" for XML)    
      produces:
        - text/html
        - application/json
        - application/xml
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/StyleList"
          examples:
            application/json: {
                "styles": {
                    "style": [
                        {
                            "href": "http://localhost:8080/geoserver/rest/styles/burg.json",
                            "name": "burg"
                        },
                        {
                            "href": "http://localhost:8080/geoserver/rest/styles/capitals.json",
                            "name": "capitals"
                        }
                    ]
                }
            }
            application/xml: '
              <styles>
                  <style>
                      <name>burg</name>
                      <atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://localhost:8080/geoserver/rest/styles/burg.xml" type="application/xml"/>
                  </style>
                  <style>
                      <name>capitals</name>
                      <atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://localhost:8080/geoserver/rest/styles/capitals.xml" type="application/xml"/>
                  </style>    
              </styles>'
        401:
          description: Full authentication is required to access this resource
    post:
      operationId: postStyle
      summary: Add a new style
      description: Adds a new style to the server.
      parameters:
        - name: styleBody
          description: The style body to upload.
          in: body
          required: true          
          schema:
            $ref: "#/definitions/StyleInfoPost"
      consumes:
        - application/vnd.ogc.sld+xml
        - application/vnd.ogc.se+xml
        - application/zip
      produces:
        - application/xml
        - text/html
        - application/json
      responses:
        201:
          description: Created
          schema:
            type: string
        401:
          description: Unauthorized    
  /styles/{styleName}:   
    parameters:
      - name: styleName
        in: Path
        required: true
        description: The name of the style to retrieve
        type: string
      - name: purge
        in: Query
        required: false
        description: The purge parameter specifies whether the underlying SLD file for the style should be deleted on disk. Allowable values for this parameter are “true” or “false”. When set to “true” the underlying file will be deleted.
        type: boolean                         
    get:
      operationId: getStyle
      summary: Get a single style
      description: Controls a given style.
      produces:
        - text/html
        - application/json
        - application/xml
        - application/vnd.ogc.sld+xml
      parameters:
        - name: quietOnNotFound 
          in: Query
          required: false
          description: The quietOnNotFound parameter avoids to log an Exception when the style is not present. Note that 404 status code will be returned anyway.
          type: boolean             
        - name: pretty
          in: Query
          required: false
          description: The pretty parameter returns the style in a human-readable format, with proper whitespace and indentation. This parameter has no effect if you request a style in its native format - in this case the API returns the exact content of the underlying file. The HTML, XML, and JSON formats do not support this parameter.
          type: boolean      
      responses:
        200:
          description: OK
          examples:
            application/json: { "style": {
                                  "name": "rain",
                                  "format": "sld",
                                  "languageVersion": {
                                    "version": "1.0.0"
                                  },
                                  "filename": "rain.sld"
                                }
                              }
            application/xml: '<style>
                                  <name>rain</name>
                                  <format>sld</format>
                                  <languageVersion>
                                      <version>1.0.0</version>
                                  </languageVersion>
                                  <filename>rain.sld</filename>
                              </style>' 
            application/vnd.ogc.sld+xml: '<?xml version="1.0" encoding="UTF-8"?>
                                <StyledLayerDescriptor version="1.0.0" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc"
                                  xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                  xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd">
                                    <NamedLayer>
                                        <Name>rain</Name>
                                        <UserStyle>
                                            <Name>rain</Name>
                                            <Title>Rain distribution</Title>
                                            <FeatureTypeStyle>
                                                <Rule>
                                                    <RasterSymbolizer>
                                                        <Opacity>1.0</Opacity>
                                                        <ColorMap>
                                                            <ColorMapEntry color="#FF0000" quantity="0" />
                                                            <ColorMapEntry color="#FFFFFF" quantity="100"/>
                                                            <ColorMapEntry color="#00FF00" quantity="2000"/>
                                                            <ColorMapEntry color="#0000FF" quantity="5000"/>
                                                        </ColorMap>
                                                    </RasterSymbolizer>
                                                </Rule>
                                            </FeatureTypeStyle>
                                        </UserStyle>
                                    </NamedLayer>
                                </StyledLayerDescriptor>'
        401:
          description: Full authentication is required to access this resource        
    delete:
      operationId: deleteStyle
      summary: Delete a style
      description: Delete a style
      parameters:
        - name: recurse
          in: Query
          required: false
          description: The recurse parameter removes references to the specified style in existing layers. Allowed values for this parameter are “true” or “false”. The default value is “false”.
          type: boolean  
      responses:
        200:
          description: The style was successfully deleted.
        401:
          description: Full authentication is required to access this resource              
    put:
      operationId: putStyle
      summary: Modify a single style
      description: Modify a single style
      parameters:
        - name: raw
          in: query
          description: The raw parameter specifies whether to forgo parsing and encoding of the uploaded style content. When set to true the style payload will be streamed directly to GeoServer configuration. Use this setting if the content and formatting of the style is to be preserved exactly. Use this setting with care as it may result in an invalid and unusable style. The default is false.
          type: boolean
          required: false
        - name: styleBody
          in: body
          description: The updated style body.
          required: true
          schema:
            $ref: "#/definitions/StylePutBody"
      consumes:
        - application/json
        - application/xml
        - application/vnd.ogc.sld+xml
      responses:
        200:
          description: The style was successfully updated.

definitions:
  StyleInfoPost:
    type: object
    example: {"text/xml": "<style><name>roads_style</name><afilename>roads.sld</filename></style>"}
    required: [name, filename]
    properties:
      name:
        type: string
        description: Name of style
      filename:
        type: string
        description: name of filename
  StyleListItem:
    type: object
    properties:
      name:
        type: string
        description: ""
      href:
        type: string
        description: ""
  StyleList:
    type: array
    items:
      $ref: '#/definitions/StyleListItem'
  StylePutBody:
    type: String
    description: The style body.
    example: "/* @title gold point */
              * {
                  mark: symbol(square);
                  mark-size: 6px;
                  :mark {
                      fill: #ffcc00;
                  }
              }"