sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
before_script:
  - cd src
script:
  - rm -rf /home/travis/.m2/repository/org/apache/xmlgraphics/fop
  - mvn -B -U -T2 -fae -Prelease clean install -Dtest.maxHeapSize=512M -Djava.awt.headless=true
notifications:
  email:
    on_success: never
    on_failure: never
jdk:
  - oraclejdk7
  - oraclejdk8
branches:
  only:
    - master
    - 2.8.x
os:
  - linux
  - osx
matrix: 
  allow_failures:
    - os: osx
  exclude:
    - branch: master 
      jdk: oraclejdk7
  include:
    - os: linux
      jdk: openjdk7
