sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
before_script:
  - cd src
script:
  - rm -rf /home/travis/.m2/repository/org/apache/xmlgraphics/fop
  - mvn -B -U -T2 -fae -Prelease clean install -Dtest.maxHeapSize=512M -Djava.awt.headless=true
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
    - master
    - 2.8.x
matrix: 
  allow_failures:
    - os: osx
  exclude:
    - branch: master 
      jdk: oraclejdk7
  include:
    - os: linux
      jdk: openjdk7
      branch: 2.8.x
    - os: linux
      jdk: oraclejdk7
      branch: 2.8.x
    - os: linux
      jdk: oraclejdk8
      branch: master
    - os: osx
      branch: 2.8.x
    - os: osx
      branch: master
before_install:
   # JAVA_HOME is not available on OSX, set it to allow Maven run
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
