---
swagger: '2.0'
info:
  version: 1.0.0
  title: GeoServer Layer Groups
  description: A layer group is a group of layers that can be referenced as a single layer as part of a WMS request. A layer group can also be used as a container for layers.

paths:
  /layergroups:
    get:
      operationId: getLayergroups
      summary: Get a list of layer groups
      description: Displays a list of all layer groups on the server not otherwise in a workspace. Use the "Accept:" header to specify format or append an extension to the endpoint (example "/layergroups.xml" for XML)
      produces:
        - text/html
        - application/json
        - application/xml
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/LayergroupResponse"
          examples:
            application/json: '
              {"layerGroups":{"layerGroup":[{"name":"spearfish","href":"http:\/\/localhost:8080\/geoserver\/rest\/layergroups\/spearfish.json"},{"name":"tasmania","href":"http:\/\/localhost:8080\/geoserver\/rest\/layergroups\/tasmania.json"},{"name":"tiger-ny","href":"http:\/\/localhost:8080\/geoserver\/rest\/layergroups\/tiger-ny.json"}]}}
            '
            application/xml: '
              <layerGroups>
                <layerGroup>
                  <name>spearfish</name>
                  <atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://localhost:8080/geoserver/rest/layergroups/spearfish.xml" type="application/xml"/>
                </layerGroup>
              </layerGroups>
            '

    post:
      operationId: postLayergroups
      summary: Add a new layer group
      description: Adds a new layer group entry to the server.

      parameters:
        - name: layergroupBody
          description: The layer group body information to upload.
          in: body
          required: true          
          schema:
            $ref: "#/definitions/Layergroup"
      consumes:
        - application/xml
        - application/zip
      produces:
        - application/xml
        - text/html
        - application/json
      responses:
        201:
          description: Created
          schema:
            type: string
          headers:
            Location:
              description: URL where the newly created layer group can be found
              type: string

    put:
      operationId: putLayergroups
      description: Invalid. Use POST for adding a new layer group, or PUT on /layergroups/{layergroup} to edit an existing layer group.
      responses:
        405:
          description: Method Not Allowed

    delete:
      operationId: deleteLayergroups
      description: Invalid. Use /layergroups/{layergroup} instead.
      responses:
        405:
          description: Method Not Allowed

  /layergroups/{layergroupName}:
    get:
      operationId: getLayergroup
      summary: Retrieve a layer group
      description: Retrieves a single layer group definition. Use the "Accept:" header to specify format or append an extension to the endpoint (example "/layergroups/{layergroup}.xml" for XML).
      produces:
        - text/html
        - application/json
        - application/xml
      parameters:
        - name: layergroupName
          in: path
          required: true
          description: The name of the layergroup to retrieve.
          type: string
        - name: quietOnNotFound 
          in: query
          required: false
          description: The quietOnNotFound parameter avoids logging an exception when the layer group is not present. Note that 404 status code will still be returned.
          type: boolean             
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Layergroup"
          examples:
            text/html: '
              <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
              <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
              <head>
                  <title>GeoServer Configuration</title>
                  <meta name="ROBOTS" content="NOINDEX, NOFOLLOW"/>
              </head>
              <body>
              
              Layer group "spearfish"
              
              <ul>
                <li>Name: spearfish</li>
                <li>Layers: [LayerInfoImpl[sfdem, resource:CoverageInfoImpl[sfdem]], LayerInfoImpl[streams, resource:FeatureTypeInfoImpl[streams]], i>Styles: [StyleInfoImpl[dem], null]</li>
              </ul>
              
              </body>
              </html>
              '
            application/json: '
              {"layerGroup":{"name":"spearfish","mode":"SINGLE","title":"Spearfish","abstractTxt":"Spearfish City in Lawrence County, South Dakota","publishables":{"published":[{"@type":"layer","name":"sfdem","href":"http://localhost:8080/geoserver/rest/layers/sfdem.json"},{"@type":"layer","name":"streams","href":"http://localhost:8080/geoserver/rest/layers/streams.json"}]},"styles":{"style":[{"name":"dem","href":"http://localhost:8080/geoserver/rest/styles/dem.json"},"null"]},"bounds":{"minx":589425.9342365642,"maxx":609518.6719560538,"miny":4913959.224611808,"maxy":4928082.949945881,"crs":{"@class":"projected","$":"EPSG:26713"}},"metadata":{"entry":{"@key":"rawStyleList","$":""}}}}
              '
            application/xml: '
              <layerGroup>
                <name>spearfish</name>
                <mode>SINGLE</mode>
                <title>Spearfish</title>
                <abstractTxt>Spearfish City in Lawrence County, South Dakota</abstractTxt>
                <publishables>
                  <published type="layer">
                    <name>sfdem</name>
                    <atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://localhost:8080/geoserver/rest/layers/sfdem.xml" type="application/xml"/>
                  </published>
                  <published type="layer">
                    <name>streams</name>
                    <atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://localhost:8080/geoserver/rest/layers/streams.xml" type="application/xml"/>
                  </published>
                </publishables>
                <styles>
                  <style>
                    <name>dem</name>
                      <atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://localhost:8080/geoserver/rest/styles/dem.xml" type="application/xml"/>
                  <style/>
                </styles>
                <bounds>
                  <minx>589425.9342365642</minx>
                  <maxx>609518.6719560538</maxx>
                  <miny>4913959.224611808</miny>
                  <maxy>4928082.949945881</maxy>
                  <crs class="projected">EPSG:26713</crs>
                </bounds>
                <metadata>
                  <entry key="rawStyleList"></entry>
                </metadata>
              </layerGroup>
              '

    post:
      operationId: postLayergroup
      description: Invalid. Use PUT to edit a layer group definition, or POST with /layergroups to add a new definition.
      responses:
        405:
          description: Method Not Allowed

    put:
      operationId: putLayergroup
      summary: Modify a layer group.
      description: Modifies an existing layer group on the server. Use the "Accept:" header to specify format or append an extension to the endpoint (example "/layergroups/{layergroup}.xml" for XML).
      parameters:
        - name: layergroupName
          in: path
          required: true
          description: The name of the layergroup to modify.
          type: string
        - name: layergroupBody
          in: body
          description: The updated layer group definition.
          required: true
          schema:
            $ref: "#/definitions/Layergroup"
      consumes:
        - application/xml
        - application/json
      responses:
        200:
          description: The layer group was successfully updated.

    delete:
      operationId: deleteLayergroup
      summary: Delete layer group
      description: Deletes a layer group from the server.
      parameters:
        - name: layergroupName
          in: path
          required: true
          description: The name of the layer group to delete.
          type: string
      responses:
        200:
          description: OK

definitions:

  LayergroupResponse:
    type: object
    properties:
      layerGroups:
        $ref: '#/definitions/Layergroups'

  Layergroups:
    title: layerGroup
    type: object
    properties:
      layerGroup: 
        $ref: '#/definitions/LayergroupWrapper'

  LayergroupWrapper:
    type: array
    items:
      $ref: '#/definitions/LayergroupListItem'

  LayergroupListItem:
    type: object
    properties:
      name:
        type: string
        description: Name of layer group
      link:
        type: string
        description: URL to layer group definition

  Layergroup:
    type: object
    properties:
      name:
        type: string
        description: Name of the layer group
      mode:
        type: string
        enum: 
        - SINGLE
        - NAMED
        - CONTAINER
        - EO
        description: Name of the layer group mode. Can be SINGLE, NAMED, CONTAINER, or EO.
      title:
        type: string
        description: Title of the layer group
      abstractTxt:
        type: string
        description: Abstract of the layer group
      publishables:
        type: array
        items:
          $ref: '#/definitions/LayergroupPublished'
      styles:
        type: array
        items:
          $ref: '#/definitions/LayergroupStyle'
      metadataLinks:
        type: array
        items:
          $ref: '#/definitions/LayergroupMetadataLink'
      bounds:
        type: object
        properties:
          minx:
            type: number
            description: Minimum X value of bounds
          maxx:
            type: number
            description: Maximum X value of bounds
          miny:
            type: number
            description: Minimum Y value of bounds
          maxy:
            type: number
            description: Maximum Y value of bounds            
          crs:
            type: string
            description: CRS code, usually in the form EPSG:####

  LayergroupPublished:
    type: object
    title: published
    properties:
      name:
        type: string
        description: Name of the comprising layer
      link:
        type: string
        description: URL to the comprising layer

  LayergroupStyle:
    title: style
    type: object
    description: This object will not exist when default style is used
    properties:
      name:
        type: string
        description: Name of the style for the corresponding layer in the list
      link:
        type: string
        description: URL of the style for the corresponding layer in the list

  LayergroupMetadataLink:
    type: object
    properties:
      type:
        type: string
        description: MIME type
      metadataType:
        type: string
        description: Metadata type. Can be ISO9115:2003, FGDC, TC211, 19139, or other.
      content:
        type: string
        description: URL of metadata link
