---
swagger: '2.0'
info:
  version: 1.0.0
  title: GeoServer Template
  description: Manage templates used to configure output (for example GetFeatureInfo reponse). Templates can be registered for the entire server or workspace. You can also configure a template for use with a store, featureType or coverage.

paths:
  /templates:
    get:
      operationId: templatesGet
      summary: List of templates for the server
      description: Displays a list of templates resitered for use on the server.
      produces:
        - text/plain
      responses:
        200
  /workspaces/{workspace}/templates:
    get:
      operationId: templatesWorkspaceGet
      summary: List of templates for workspace
      description: Displays a list of templates resitered for use in a workspace
      produces:
        - text/plain
      responses:
        200
  /workspaces/{workspace}/datastores/{store}/templates:
    get:
      operationId: templatesDataStoreGet
      summary: List of templates for a DataStore
      description: Displays a list of templates resitered for use by all layers generated by a DataStore
      produces:
        - text/plain
      responses:
        200
  /workspaces/{workspace}/datastores/{store}/featuretypes/{type}/templates:
    get:
      operationId: templatesDataStoreGet
      summary: List of templates for a DataStore
      description: Displays a list of templates resitered for use by all layers generated by a DataStore
      produces:
        - text/plain
      responses:
        200