---
swagger: '2.0'
info:
  version: 1.0.0
  title: GeoServer Workspaces
  description: A workspace is a group or folder of data stores for publishing. A workspace can be accessed as a virtual open webservice, or simply used to group related information.

paths:
  /workspaces:
    $ref: "./workspaces.yaml#/paths/WorkspacesPath"
